# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib SA24204143
#' @import Rcpp
NULL

#' @name karatsubaMultiplyRcpp
#' @title Karatsuba Multiplication Function in C++
#' @description This function implements the Karatsuba algorithm to multiply two large numbers represented as strings.
#' @param num1 The first number in string format to be multiplied.
#' @param num2 The second number in string format to be multiplied.
#' @return The product of the two input numbers in string format.
#' @examples
#' \dontrun{
#' std::string num1 = "123456789";
#' std::string num2 = "987654321";
#' std::string result = karatsubaMultiplyRcpp(num1, num2);
#' Rcpp::Rcout << result << std::endl;
#' }
#' @export
karatsubaMultiplyRcpp <- function(num1, num2) {
    .Call('_SA24204143_karatsubaMultiplyRcpp', PACKAGE = 'SA24204143', num1, num2)
}

